#!/usr/bin/env python3
"""USAGE
    zpkg [-g] {add,package,ls,clear,rm} ...

SUBCOMMANDS
    add [PKG] BUILD-ARGS   builds and adds a package
    clear                  clean build cache
    ls                     lists all installed packages
    package PKG FILE       creates an universal package
    rm PKG                 uninstalls the given package

ARGUMENTS
    --global, -g
        affects the system globally

BUILD ARGUMENTS
    --from, -f
        choose a base image
    --run, -x
        run any shell (/bin/sh) command
    --layer, -l
        adds a layer for build caching
    --from-github
        build according to instructions at GitHub project
    --add-apt-repository, --apt, --apk, --apt, --dnf, --emerge, --npm,
    --pacman, --pip, --pip3, --yum
        Invokes the given tool with it's primary action

    -A  same as `--from alpine --apk`
    -C  same as `--from centos --yum`
    -D  same as `--from debian --apt`
    -F  same as `--from fedora --dnf`
    -G  same as `--from gentoo --emerge`
    -R  same as `--from archlinux --pacman`
    -U  same as `--from ubuntu --apt`

EXAMPLE
    zpkg add xeyes -U x11-apps
    zpkg add -A gimp
    zpkg add -A py3-pip --pip3 yapf
    zpkg rm yapf"""

import sys, os, subprocess, shutil, tempfile, shlex
from os.path import join

dir_path = os.path.dirname(os.path.realpath(__file__))
BCHROOT_FILE = join(dir_path, 'bchroot')
BOOTSTRAP_SCRIPT = join(dir_path, 'bootstrap.sh')

os.environ["PATH"] = ":".join([join(dir_path, "plash/bin")] +
                              os.environ.get("PATH").split(":"))

if len(sys.argv) > 1 and sys.argv[1] in ('-g', '--global'):
    sys.argv.pop(1)
    DATADIR = "/usr/local/lib/zpkg"
    BINDIR = "/usr/local/bin"
    PLASH_DATA = "/var/cache/zpkg"
else:
    DATADIR = os.path.expanduser("~/.local/lib/zpkg")
    BINDIR = os.path.expanduser("~/.local/bin")
    PLASH_DATA = os.path.expanduser("~/.cache/zpkg")
os.environ["PLASH_DATA"] = PLASH_DATA

LIST_ALL_CMD = [
    'sh', '-c',
    "echo -n $PATH | tr : '\n' | xargs -I {} find {} -maxdepth 1 -perm /u=x,g=x,o=x \( -type f -or -type l \) 2> /dev/null | sort -u"
]


def usage():
    print(__doc__)
    sys.exit(1)


def die(msg):
    print("zpkg error: {}".format(msg), file=sys.stderr)
    sys.exit(1)


def info(msg):
    print("zpkg: {}".format(msg), file=sys.stderr)


def plash_call(*args):
    try:
        return subprocess.check_output(["plash"] +
                                       list(args)).decode().strip("\n")
    except subprocess.CalledProcessError as exc:
        sys.exit(1)


def very_magic_guess(newcmds, buildargs):
    if not newcmds:
        die("no new command found after build finished")
    if len(newcmds) == 1:
        return list(newcmds)[0]
    for token in buildargs:
        if token in newcmds:
            return token
    for cmd in sorted(newcmds, key=len):
        for token in buildargs:
            if token in cmd:
                return cmd
    die("unguessable command, call again specifying one of: {}".format(
        ' '.join(newcmds)))


def assert_is_installed(pkg):
    if not os.path.exists(join(DATADIR, pkg)):
        die("package {} is not installed".format(repr(pkg)))


if not len(sys.argv) >= 2:
    usage()
elif sys.argv[1] in ["-h", "--help"]:
    usage()
elif not sys.argv[1] in ["add", "ls", "rm", "clear", "package"]:
    die("no such subcommand, try --help")

os.makedirs(DATADIR, exist_ok=True)
os.makedirs(BINDIR, exist_ok=True)

if sys.argv[1] not in ("package", "ls"):
    plash_call("init")

#####
# zpkg ls
#####
if sys.argv[1] == "ls":
    for pkg in os.listdir(DATADIR):
        print(pkg)

#####
# zpkg rm
#####
elif sys.argv[1] == "rm":
    if len(sys.argv) < 3:
        die("rm PKG")
    assert_is_installed(sys.argv[2])
    cont = plash_call("map", sys.argv[2])
    if cont:
        plash_call("rm", cont)
        plash_call("clean")

    plash_call("sudo", "rm", "-rf", join(DATADIR, sys.argv[2]),
               join(BINDIR, sys.argv[2]))

#####
# zpkg clear
#####
elif sys.argv[1] == "clear":
    plash_call("purge", '--yes')

#####
# zpkg package
#####
elif sys.argv[1] == "package":
    if len(sys.argv) < 4:
        die("usage: zpkg [-g] package PROGRAM OUTFILE")
    assert_is_installed(sys.argv[2])
    plash_call("sudo", "tar", "-C", os.path.dirname(BINDIR), "-cf",
               sys.argv[3], join("bin", sys.argv[2]),
               join("lib/zpkg", sys.argv[2]))
    print(("Install package locally:\n"
           "$ tar -xf {0} -C ~/.local \n"
           "\n"
           "Install package globally:\n"
           "$ tar -xf {0} -C /usr/local").format(shlex.quote(sys.argv[3])))

#####
# zpkg add
#####
elif sys.argv[1] == "add":
    if len(sys.argv) <= 2:
        die("usage: zpkg [-g] add [PKG] BUILD-ARGS")

    if sys.argv[2].startswith("-"):
        sys.argv.insert(2, "?")

    if not sys.argv[3:]:
        die("zpkg add: build arguments missing")

    if not sys.argv[3].startswith("-"):
        die("zpkg add: build argument cannot be positional argument")

    if sys.argv[2] != '?' and os.path.exists(join(DATADIR, sys.argv[2])):
        die("package {} is already installed".format(repr(sys.argv[2])))

    tmpdir = tempfile.mkdtemp(dir=join(PLASH_DATA, "tmp"))  # reuse plash's tmp
    builded = plash_call("build", "--hash-path", BOOTSTRAP_SCRIPT, "-x",
                         BOOTSTRAP_SCRIPT, "--layer", *sys.argv[2:])
    plash_call("shallow-copy", builded, join(tmpdir, "rootfs"))
    os.chmod(join(tmpdir, "rootfs"), 0o755)
    parent = plash_call("parent", builded)
    orig_cmds = set(plash_call('run', parent, *LIST_ALL_CMD).splitlines())
    after_cmds = set(plash_call('run', builded, *LIST_ALL_CMD).splitlines())
    new_cmds = sorted([os.path.basename(i) for i in (after_cmds - orig_cmds)])

    if not new_cmds:
        die("no new binaries found")
    if sys.argv[2] == "?":
        sys.argv[2] = very_magic_guess(new_cmds, sys.argv[3:])
        info("guessed your command name: {}".format(sys.argv[2]))
    elif sys.argv[2] not in new_cmds:
        die("command {} not found after build finished, but there is: {}".
            format(repr(sys.argv[2]), ' '.join(new_cmds)))
    if os.path.exists(join(DATADIR, sys.argv[2])):
        die("package {} is already installed".format(repr(sys.argv[2])))

    targetdir = join(DATADIR, sys.argv[2])
    launcher = join(BINDIR, sys.argv[2])
    os.link(BCHROOT_FILE, join(tmpdir, sys.argv[2]))
    os.rename(tmpdir, targetdir)
    os.chmod(targetdir, 0o755)
    try:
        os.unlink(launcher)
    except FileNotFoundError:
        pass
    os.symlink(join("../lib/zpkg", sys.argv[2], sys.argv[2]), launcher)

    home = os.path.expanduser('~')
    datadir = targetdir.replace(home, '~')
    launcher = launcher.replace(home, '~')
    print("zpkg: succesfully installed {} to {}, linked to {}".format(
        repr(sys.argv[2]), datadir, launcher))
    #print("linked to: {}".format(launcher))

    # map it, so it can be deleted
    plash_call("map", sys.argv[2], builded)
